export type ImportantPlayerSeed = {
  name: string;
  club: string;
  marketValueM: number;
};

export const IMPORTANT_PLAYERS_CATALOG: ImportantPlayerSeed[] = [
  { name: 'Erling Haaland', club: 'Manchester City', marketValueM: 200 },
  { name: 'Bukayo Saka', club: 'Arsenal', marketValueM: 130 },
  { name: 'Declan Rice', club: 'Arsenal', marketValueM: 120 },
  { name: 'Cole Palmer', club: 'Chelsea', marketValueM: 120 },
  { name: 'Alexander Isak', club: 'Liverpool', marketValueM: 120 },
  { name: 'Moises Caicedo', club: 'Chelsea', marketValueM: 110 },
  { name: 'Florian Wirtz', club: 'Liverpool', marketValueM: 110 },
  { name: 'William Saliba', club: 'Arsenal', marketValueM: 90 },
  { name: 'Ryan Gravenberch', club: 'Liverpool', marketValueM: 90 },
  { name: 'Enzo Fernandez', club: 'Chelsea', marketValueM: 85 },
  { name: 'Dominik Szoboszlai', club: 'Liverpool', marketValueM: 85 },
  { name: 'Alexis Mac Allister', club: 'Liverpool', marketValueM: 85 },
  { name: 'Hugo Ekitike', club: 'Liverpool', marketValueM: 85 },
  { name: 'Estevao', club: 'Chelsea', marketValueM: 80 },
  { name: 'Phil Foden', club: 'Manchester City', marketValueM: 80 },
  { name: 'Martin Odegaard', club: 'Arsenal', marketValueM: 75 },
  { name: 'Martin Zubimendi', club: 'Arsenal', marketValueM: 75 },
  { name: 'Gabriel Magalhaes', club: 'Arsenal', marketValueM: 75 },
  { name: 'Sandro Tonali', club: 'Newcastle', marketValueM: 75 },
  { name: 'Rodri', club: 'Manchester City', marketValueM: 75 },
  { name: 'Federico Valverde', club: 'Chelsea', marketValueM: 75 },
  { name: 'Julian Alvarez', club: 'Atletico Madrid', marketValueM: 75 },
  { name: 'Myles Lewis-Skelly', club: 'Arsenal', marketValueM: 70 },
  { name: 'Jeremy Frimpong', club: 'Liverpool', marketValueM: 70 },
  { name: 'Matheus Cunha', club: 'Manchester United', marketValueM: 70 },
  { name: 'Jurrien Timber', club: 'Arsenal', marketValueM: 70 },
  { name: 'Cody Gakpo', club: 'Liverpool', marketValueM: 70 },
  { name: 'Viktor Gyokeres', club: 'Arsenal', marketValueM: 70 },
  { name: 'Joao Pedro', club: 'Chelsea', marketValueM: 65 },
  { name: 'Omar Marmoush', club: 'Manchester City', marketValueM: 65 },
  { name: 'Tijjani Reijnders', club: 'Manchester City', marketValueM: 65 },
  { name: 'Jeremy Doku', club: 'Manchester City', marketValueM: 65 },
  { name: 'Eberechi Eze', club: 'Arsenal', marketValueM: 65 },
  { name: 'Antoine Semenyo', club: 'Manchester City', marketValueM: 65 },
  { name: 'Micky van de Ven', club: 'Tottenham', marketValueM: 65 },
  { name: 'Morgan Gibbs-White', club: 'Nottingham Forest', marketValueM: 65 },
  { name: 'Ruben Dias', club: 'Manchester City', marketValueM: 60 },
  { name: 'Carlos Baleba', club: 'Brighton', marketValueM: 60 },
  { name: 'Xavi Simons', club: 'Tottenham', marketValueM: 60 },
  { name: 'Elliot Anderson', club: 'Nottingham Forest', marketValueM: 60 },
  { name: 'Benjamin Sesko', club: 'Manchester United', marketValueM: 60 },
  { name: 'Anthony Gordon', club: 'Newcastle', marketValueM: 60 },
  { name: 'Cristian Romero', club: 'Tottenham', marketValueM: 60 },
  { name: 'Adam Wharton', club: 'Crystal Palace', marketValueM: 60 },
  { name: 'Pedro Neto', club: 'Chelsea', marketValueM: 60 },
  { name: 'Marc Guehi', club: 'Manchester City', marketValueM: 55 },
  { name: 'Mohammed Kudus', club: 'Tottenham', marketValueM: 55 },
  { name: 'Leny Yoro', club: 'Manchester United', marketValueM: 55 },
  { name: 'Murillo', club: 'Nottingham Forest', marketValueM: 55 },
  { name: 'Amad Diallo', club: 'Manchester United', marketValueM: 50 },
  { name: 'Riccardo Calafiori', club: 'Arsenal', marketValueM: 50 },
  { name: 'Noni Madueke', club: 'Arsenal', marketValueM: 50 },
  { name: 'Piero Hincapie', club: 'Arsenal', marketValueM: 50 },
  { name: 'Anthony Elanga', club: 'Newcastle', marketValueM: 50 },
  { name: 'Rayan Cherki', club: 'Manchester City', marketValueM: 50 },
  { name: 'Ibrahima Konate', club: 'Liverpool', marketValueM: 50 },
  { name: 'Marc Cucurella', club: 'Chelsea', marketValueM: 50 },
  { name: 'Reece James', club: 'Chelsea', marketValueM: 50 },
  { name: 'Levi Colwill', club: 'Chelsea', marketValueM: 50 },
  { name: 'Gabriel Martinelli', club: 'Arsenal', marketValueM: 45 },
  { name: 'Iliman Ndiaye', club: 'Everton', marketValueM: 45 },
  { name: 'Jarrad Branthwaite', club: 'Everton', marketValueM: 45 },
  { name: 'Savinho', club: 'Manchester City', marketValueM: 45 },
  { name: 'Alejandro Garnacho', club: 'Chelsea', marketValueM: 45 },
  { name: 'Nico Gonzalez', club: 'Manchester City', marketValueM: 45 },
  { name: 'Gianluigi Donnarumma', club: 'Manchester City', marketValueM: 45 },
  { name: 'Dejan Kulusevski', club: 'Tottenham', marketValueM: 45 },
  { name: 'Amadou Onana', club: 'Aston Villa', marketValueM: 42 },
  { name: 'Mohamed Salah', club: 'Liverpool', marketValueM: 30 },
  { name: 'Bruno Fernandes', club: 'Manchester United', marketValueM: 40 },
  { name: 'Matthijs de Ligt', club: 'Manchester United', marketValueM: 40 },
  { name: 'Kobbie Mainoo', club: 'Manchester United', marketValueM: 40 },
  { name: 'Boubacar Kamara', club: 'Aston Villa', marketValueM: 40 },
  { name: 'Evanilson', club: 'AFC Bournemouth', marketValueM: 40 },
  { name: 'Lisandro Martinez', club: 'Manchester United', marketValueM: 40 },
  { name: 'Jarrod Bowen', club: 'West Ham', marketValueM: 40 },
  { name: 'Joao Gomes', club: 'Wolves', marketValueM: 40 },
  { name: 'Kaoru Mitoma', club: 'Brighton', marketValueM: 40 },
  { name: 'Liam Delap', club: 'Chelsea', marketValueM: 40 },
  { name: 'Romeo Lavia', club: 'Chelsea', marketValueM: 40 },
  { name: 'Rico Lewis', club: 'Manchester City', marketValueM: 40 },
  { name: 'Tino Livramento', club: 'Newcastle', marketValueM: 40 },
  { name: 'Dominic Solanke', club: 'Tottenham', marketValueM: 40 },
  { name: 'Brennan Johnson', club: 'Tottenham', marketValueM: 40 },
  { name: 'Destiny Udogie', club: 'Tottenham', marketValueM: 40 },
  { name: 'Bernardo Silva', club: 'Manchester City', marketValueM: 38 },
  { name: 'Archie Gray', club: 'Tottenham', marketValueM: 38 },
  { name: 'Lucas Bergvall', club: 'Tottenham', marketValueM: 38 },
  { name: 'Youri Tielemans', club: 'Aston Villa', marketValueM: 38 },
  { name: 'Pedro Porro', club: 'Tottenham', marketValueM: 38 },
  { name: 'Ezri Konsa', club: 'Aston Villa', marketValueM: 35 },
  { name: 'Joelinton', club: 'Newcastle', marketValueM: 35 },
  { name: 'Georginio Rutter', club: 'Brighton', marketValueM: 32 },
  { name: 'Justin Kluivert', club: 'AFC Bournemouth', marketValueM: 32 },
  { name: 'Djed Spence', club: 'Tottenham', marketValueM: 32 },
  { name: 'Mason Mount', club: 'Manchester United', marketValueM: 32 },
  { name: 'Lewis Hall', club: 'Newcastle', marketValueM: 32 },
  { name: 'Habib Diarra', club: 'Sunderland', marketValueM: 32 },
  { name: 'Harvey Barnes', club: 'Newcastle', marketValueM: 32 },
  { name: 'Dilane Bakwa', club: 'Nottingham Forest', marketValueM: 32 },
  { name: 'Mateus Fernandes', club: 'West Ham', marketValueM: 32 },
  { name: 'Ben White', club: 'Arsenal', marketValueM: 30 },
  { name: 'Mikel Merino', club: 'Arsenal', marketValueM: 30 },
  { name: 'Yasin Ayari', club: 'Brighton', marketValueM: 30 },
  { name: 'Tyler Dibling', club: 'Everton', marketValueM: 30 },
  { name: 'Thierno Barry', club: 'Everton', marketValueM: 30 },
  { name: 'Mikkel Damsgaard', club: 'Brentford', marketValueM: 30 },
  { name: 'Conor Bradley', club: 'Liverpool', marketValueM: 30 },
  { name: 'Alex Scott', club: 'AFC Bournemouth', marketValueM: 30 },
  { name: 'Guglielmo Vicario', club: 'Tottenham', marketValueM: 30 },
  { name: 'James Maddison', club: 'Tottenham', marketValueM: 30 },
  { name: 'Patrick Dorgu', club: 'Manchester United', marketValueM: 30 },
  { name: 'Mathys Tel', club: 'Tottenham', marketValueM: 30 },
  { name: 'Manuel Ugarte', club: 'Manchester United', marketValueM: 30 },
  { name: 'Cheick Doucoure', club: 'Crystal Palace', marketValueM: 25 },
  { name: 'Andre Onana', club: 'Manchester United', marketValueM: 25 },
  { name: 'Tyrick Mitchell', club: 'Crystal Palace', marketValueM: 25 },
  { name: 'Noussair Mazraoui', club: 'Manchester United', marketValueM: 25 },
  { name: 'Dwight McNeil', club: 'Everton', marketValueM: 25 },
  { name: 'Callum Hudson-Odoi', club: 'Nottingham Forest', marketValueM: 25 },
  { name: 'Sander Berge', club: 'Fulham', marketValueM: 25 },
  { name: 'Calvin Bassey', club: 'Fulham', marketValueM: 25 },
  { name: 'Aaron Wan-Bissaka', club: 'West Ham', marketValueM: 24 },
  { name: 'Jack Hinshelwood', club: 'Brighton', marketValueM: 24 },
  { name: 'Ibrahim Sangare', club: 'Nottingham Forest', marketValueM: 24 },
  { name: 'Keane Lewis-Potter', club: 'Brentford', marketValueM: 23 },
  { name: 'Virgil van Dijk', club: 'Liverpool', marketValueM: 23 },
  { name: 'Leandro Trossard', club: 'Arsenal', marketValueM: 22 },
  { name: 'Axel Disasi', club: 'Aston Villa', marketValueM: 22 },
  { name: 'Marcos Senesi', club: 'AFC Bournemouth', marketValueM: 22 },
  { name: 'Crysencio Summerville', club: 'West Ham', marketValueM: 22 },
  { name: 'Sepp van den Berg', club: 'Brentford', marketValueM: 22 },
  { name: "Matt O'Riley", club: 'Brighton', marketValueM: 22 },
  { name: 'Benoit Badiashile', club: 'Chelsea', marketValueM: 22 },
  { name: 'Taylor Harwood-Bellis', club: 'Southampton', marketValueM: 22 },
  { name: 'Omari Hutchinson', club: 'Ipswich', marketValueM: 22 },
  { name: 'Julio Enciso', club: 'Ipswich', marketValueM: 22 },
  { name: 'Kylian Mbappe', club: 'Real Madrid', marketValueM: 200 },
  { name: 'Lamine Yamal', club: 'FC Barcelona', marketValueM: 200 },
  { name: 'Jude Bellingham', club: 'Real Madrid', marketValueM: 160 },
  { name: 'Vinicius Junior', club: 'Real Madrid', marketValueM: 150 },
  { name: 'Pedri', club: 'FC Barcelona', marketValueM: 140 },
  { name: 'Julian Alvarez', club: 'Atletico Madrid', marketValueM: 100 },
  { name: 'Arda Guler', club: 'Real Madrid', marketValueM: 90 },
  { name: 'Raphinha', club: 'FC Barcelona', marketValueM: 90 },
  { name: 'Pau Cubarsi', club: 'FC Barcelona', marketValueM: 80 },
  { name: 'Rodrygo', club: 'Real Madrid', marketValueM: 80 },
  { name: 'Dean Huijsen', club: 'Real Madrid', marketValueM: 70 },
  { name: 'Fermin Lopez', club: 'FC Barcelona', marketValueM: 60 },
  { name: 'Jules Kounde', club: 'FC Barcelona', marketValueM: 60 },
  { name: 'Pablo Barrios', club: 'Atletico Madrid', marketValueM: 60 },
  { name: 'Nico Williams', club: 'Athletic Club', marketValueM: 60 },
  { name: 'Alex Baena', club: 'Atletico Madrid', marketValueM: 55 },
  { name: 'Ferran Torres', club: 'FC Barcelona', marketValueM: 50 },
  { name: 'Frenkie de Jong', club: 'FC Barcelona', marketValueM: 45 },
  { name: 'Giuliano Simeone', club: 'Atletico Madrid', marketValueM: 40 },
  { name: 'Gavi', club: 'FC Barcelona', marketValueM: 40 },
  { name: 'Oihan Sancet', club: 'Athletic Club', marketValueM: 40 },
  { name: 'Yeremy Pino', club: 'Villarreal CF', marketValueM: 38 },
  { name: 'Takefusa Kubo', club: 'Real Sociedad', marketValueM: 35 },
  { name: 'Guillermo Maripan', club: 'Real Sociedad', marketValueM: 30 },
  { name: 'Nabil Fekir', club: 'Real Betis', marketValueM: 30 },
  { name: 'Andriy Lunin', club: 'Real Madrid', marketValueM: 30 },
  { name: 'Thibaut Courtois', club: 'Real Madrid', marketValueM: 25 },
  { name: 'Marc Bartra', club: 'Real Betis', marketValueM: 28 },
  { name: 'Angel Correa', club: 'Atletico Madrid', marketValueM: 28 },
  { name: 'Brais Mendez', club: 'Celta de Vigo', marketValueM: 25 },
  { name: 'Espinoza', club: 'Girona FC', marketValueM: 25 },
  { name: 'Ruben Sobrino', club: 'Real Sociedad', marketValueM: 22 },
  { name: 'Jamal Musiala', club: 'Bayern Munich', marketValueM: 140 },
  { name: 'Michael Olise', club: 'Bayern Munich', marketValueM: 130 },
  { name: 'Harry Kane', club: 'Bayern Munich', marketValueM: 65 },
  { name: 'Luis Diaz', club: 'Bayern Munich', marketValueM: 70 },
  { name: 'Dayot Upamecano', club: 'Bayern Munich', marketValueM: 70 },
  { name: 'Nicolas Jackson', club: 'Bayern Munich', marketValueM: 45 },
  { name: 'Alphonso Davies', club: 'Bayern Munich', marketValueM: 50 },
  { name: 'Joshua Kimmich', club: 'Bayern Munich', marketValueM: 45 },
  { name: 'Aleksandar Pavlovic', club: 'Bayern Munich', marketValueM: 55 },
  { name: 'Matthijs de Ligt', club: 'Borussia Dortmund', marketValueM: 77 },
  { name: 'Benjamin Sesko', club: 'Borussia Dortmund', marketValueM: 76 },
  { name: 'Xavi Simons', club: 'Borussia Dortmund', marketValueM: 60 },
  { name: 'Serhou Guirassy', club: 'Borussia Dortmund', marketValueM: 40 },
  { name: 'Nico Schlotterbeck', club: 'Borussia Dortmund', marketValueM: 55 },
  { name: 'Yann Aurel Bisseck', club: 'Eintracht Frankfurt', marketValueM: 30 },
  { name: 'Jesper Lindstrom', club: 'Eintracht Frankfurt', marketValueM: 30 },
  { name: 'Jeremie Frimpong', club: 'Bayer Leverkusen', marketValueM: 70 },
  { name: 'Victor Boniface', club: 'Bayer Leverkusen', marketValueM: 45 },
  { name: 'Robert Andrich', club: 'Bayer Leverkusen', marketValueM: 22 },
  { name: 'Kim Min-jae', club: 'Bayer Leverkusen', marketValueM: 32 },
  { name: 'Moussa Diaby', club: 'Bayer Leverkusen', marketValueM: 60 },
  { name: 'Luis Hernandez', club: 'VfB Stuttgart', marketValueM: 25 },
  { name: 'Lino Sousa', club: 'Dynamo Dresden', marketValueM: 22 },
  { name: 'Lautaro Martinez', club: 'Inter', marketValueM: 85 },
  { name: 'Alessandro Bastoni', club: 'Inter', marketValueM: 80 },
  { name: 'Nicolo Barella', club: 'Inter', marketValueM: 60 },
  { name: 'Marcus Thuram', club: 'Inter', marketValueM: 60 },
  { name: 'Hakan Calhanoglu', club: 'Inter', marketValueM: 40 },
  { name: 'Rafael Leao', club: 'AC Milan', marketValueM: 70 },
  { name: 'Theo Hernandez', club: 'AC Milan', marketValueM: 55 },
  { name: 'Christian Pulisic', club: 'AC Milan', marketValueM: 60 },
  { name: 'Fikayo Tomori', club: 'AC Milan', marketValueM: 30 },
  { name: 'Kenan Yildiz', club: 'Juventus', marketValueM: 75 },
  { name: 'Dusan Vlahovic', club: 'Juventus', marketValueM: 35 },
  { name: 'Bremer', club: 'Juventus', marketValueM: 35 },
  { name: 'Federico Chiesa', club: 'Juventus', marketValueM: 30 },
  { name: 'Victor Osimhen', club: 'Napoli', marketValueM: 75 },
  { name: 'Khvicha Kvaratskhelia', club: 'Napoli', marketValueM: 80 },
  { name: 'Scott McTominay', club: 'Napoli', marketValueM: 45 },
  { name: 'Manu Kone', club: 'Roma', marketValueM: 50 },
  { name: 'Paulo Dybala', club: 'Roma', marketValueM: 30 },
  { name: 'Teun Koopmeiners', club: 'Atalanta', marketValueM: 45 },
  { name: 'Giorgio Scalvini', club: 'Atalanta', marketValueM: 40 },
  { name: 'Ademola Lookman', club: 'Atalanta', marketValueM: 35 },
  { name: 'Joshua Zirkzee', club: 'Bologna', marketValueM: 40 },
  { name: 'Riccardo Orsolini', club: 'Bologna', marketValueM: 25 },
  { name: 'Albert Gudmundsson', club: 'Fiorentina', marketValueM: 25 },
  { name: 'Nico Gonzalez', club: 'Fiorentina', marketValueM: 25 },
  { name: 'Zlatan Ibrahimovic', club: 'AC Milan', marketValueM: 2 },
  { name: 'Juan Cuadrado', club: 'Inter', marketValueM: 3 },
  { name: 'Ciro Immobile', club: 'Lazio', marketValueM: 4 },
  { name: 'Joao Neves', club: 'PSG', marketValueM: 110 },
  { name: 'Vitinha', club: 'PSG', marketValueM: 110 },
  { name: 'Ousmane Dembele', club: 'PSG', marketValueM: 100 },
  { name: 'Desire Doue', club: 'PSG', marketValueM: 90 },
  { name: 'Khvicha Kvaratskhelia', club: 'PSG', marketValueM: 90 },
  { name: 'Achraf Hakimi', club: 'PSG', marketValueM: 80 },
  { name: 'Warren Zaire-Emery', club: 'PSG', marketValueM: 50 },
  { name: 'Randal Kolo Muani', club: 'PSG', marketValueM: 45 },
  { name: 'Fabian Ruiz', club: 'PSG', marketValueM: 40 },
  { name: 'Goncalo Ramos', club: 'PSG', marketValueM: 35 },
  { name: 'Marquinhos', club: 'PSG', marketValueM: 30 },
  { name: 'Lucas Hernandez', club: 'PSG', marketValueM: 25 },
  { name: 'Mason Greenwood', club: 'Marseille', marketValueM: 50 },
  { name: 'Pierre-Emerick Aubameyang', club: 'Marseille', marketValueM: 25 },
  { name: 'Maghnes Akliouche', club: 'Monaco', marketValueM: 45 },
  { name: 'Takumi Minamino', club: 'Monaco', marketValueM: 30 },
  { name: 'Youssouf Fofana', club: 'Monaco', marketValueM: 25 },
  { name: 'Aleksandr Golovin', club: 'Monaco', marketValueM: 25 },
  { name: 'Jonathan David', club: 'Lille', marketValueM: 40 },
  { name: 'Leny Yoro', club: 'Lille', marketValueM: 50 },
  { name: 'Benjamin Andre', club: 'Lille', marketValueM: 22 },
  { name: 'Rayan Cherki', club: 'Lyon', marketValueM: 50 },
  { name: 'Alexandre Lacazette', club: 'Lyon', marketValueM: 22 },
  { name: 'Emanuel Emegha', club: 'Strasbourg', marketValueM: 28 },
  { name: 'Wilfried Singo', club: 'Monaco', marketValueM: 25 },
  { name: 'Viktor Gyokeres', club: 'Sporting CP', marketValueM: 75 },
  { name: 'Morten Hjulmand', club: 'Sporting CP', marketValueM: 50 },
  { name: 'Ousmane Diomande', club: 'Sporting CP', marketValueM: 45 },
  { name: 'Goncalo Inacio', club: 'Sporting CP', marketValueM: 45 },
  { name: 'Pedro Goncalves', club: 'Sporting CP', marketValueM: 30 },
  { name: 'Diogo Costa', club: 'FC Porto', marketValueM: 45 },
  { name: 'Samu Aghehowa', club: 'FC Porto', marketValueM: 50 },
  { name: 'Pepe', club: 'FC Porto', marketValueM: 25 },
  { name: 'Galeno', club: 'FC Porto', marketValueM: 22 },
  { name: 'Antonio Silva', club: 'Benfica', marketValueM: 45 },
  { name: 'Goncalo Ramos', club: 'Benfica', marketValueM: 35 },
  { name: 'Florentino Luis', club: 'Benfica', marketValueM: 25 },
  { name: 'Angel Di Maria', club: 'Benfica', marketValueM: 5 },
  { name: 'Mateo Retegui', club: 'Al-Qadsiah', marketValueM: 40 },
  { name: 'Darwin Nunez', club: 'Al-Hilal', marketValueM: 35 },
  { name: 'Theo Hernandez', club: 'Al-Hilal', marketValueM: 28 },
  { name: 'Enzo Millot', club: 'Al-Ahli', marketValueM: 28 },
  { name: 'Moussa Diaby', club: 'Al-Ittihad', marketValueM: 28 },
  { name: 'Cristiano Ronaldo', club: 'Al-Nassr', marketValueM: 12 },
  { name: 'Karim Benzema', club: 'Al-Ittihad', marketValueM: 15 },
  { name: "N'Golo Kante", club: 'Al-Ittihad', marketValueM: 10 },
  { name: 'Sadio Mane', club: 'Al-Nassr', marketValueM: 18 },
  { name: 'Ruben Neves', club: 'Al-Hilal', marketValueM: 25 },
  { name: 'Joao Felix', club: 'Al-Nassr', marketValueM: 25 },
  { name: 'Roberto Firmino', club: 'Al-Ahli', marketValueM: 8 },
  { name: 'Jordan Henderson', club: 'Al-Ettifaq', marketValueM: 6 },
  { name: 'Galeno', club: 'Al-Ahli', marketValueM: 22 },
  { name: 'Lionel Messi', club: 'Inter Miami', marketValueM: 8 },
  { name: 'Luis Suarez', club: 'Inter Miami', marketValueM: 4 },
  { name: 'Sergio Busquets', club: 'Inter Miami', marketValueM: 3 },
  { name: 'Jordi Alba', club: 'Inter Miami', marketValueM: 4 },
  { name: 'Riqui Puig', club: 'LA Galaxy', marketValueM: 18 },
  { name: 'Lorenzo Insigne', club: 'Toronto FC', marketValueM: 6 },
];

export function normalizeImportantName(value: string) {
  return (value || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/\./g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

export function getImportantPlayersMap() {
  const byName = new Map<string, ImportantPlayerSeed>();
  for (const item of IMPORTANT_PLAYERS_CATALOG) {
    const key = normalizeImportantName(item.name);
    const current = byName.get(key);
    if (!current || item.marketValueM > current.marketValueM) {
      byName.set(key, item);
    }
  }
  return byName;
}
